project:
  type: book

book:
  title: "Introduction to Time Series Analysis"
  author:
    - "Yanshuo Tan"
    - "Vik Gopal"
  date: "12/30/2023"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: part1-eda.qmd
      chapters:
      - 02-tsibble.qmd
      - 03-visualization.qmd
      - 04-transformations.qmd
      - 05-decomposition.qmd
      - 06-intro_forecasting.qmd
      - 07-exponential_smoothing.qmd
      - 08-summary_stats.qmd
      - 09-spectral_analysis.qmd
    - part: part2-statistics.qmd
      chapters:
      - 10-fundamentals.qmd
      - 11-ar.qmd
      - 12-arma.qmd
      - 13-arima.qmd
      - 14-dynamic_regression.qmd
      - 15-state_space.qmd
    - part: "Advanced Topics"
      chapters:
      - 16-uncertainty.qmd
    - references.qmd
  appendices:
    - a1-rbackground.qmd
    - a2-aic.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-in-header: 
      - file: _macros.jax
  # pdf:
  #   documentclass: scrreprt
  #   code-annotations: false

publish:
  to: website
