project:
  type: book

book:
  title: "Introduction to Time Series Analysis"
  author:
    - "Yanshuo Tan"
    - "Vik Gopal"
  date: "12/30/2023"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: part1-eda.qmd
      chapters:
      - 02-tsibble.qmd
      - 03-visualization.qmd
      - 04-transformations.qmd
      - 05-decomposition.qmd
      - 06-summary_stats.qmd
      - 07-intro_forecasting.qmd
      - 08-exponential_smoothing.qmd
    - part: "Statistical Modeling of Time Series"
      chapters:
      - 09-stationary.qmd
      - 10-arma.qmd
      - 11-arima.qmd
      - 12-model_selection.qmd
      - 13-state_space.qmd
    - part: "Advanced Topics"
    - references.qmd
  appendices:
    - rbackground.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-in-header: 
      - file: _macros.jax
  # pdf:
  #   documentclass: scrreprt
  #   code-annotations: false

publish:
  to: website
