project:
  type: book

book:
  title: "Introduction to Time Series Analysis"
  author:
    - "Yanshuo Tan"
    - "Vik Gopal"
  date: "12/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - eda.qmd
    - decomposition.qmd
    - references.qmd
  # appendices:
  #   - rbackground.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



